server:
  servlet:
    context-path: /
  port: 8001

spring:
  application:
    name: user-service
  main:
    allow-bean-definition-overriding: 'true'
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8000
  r2dbc:
    password: root
    url: r2dbc:mariadb://localhost:3314/user-service-db?allowPublicKeyRetrieval=true
    username: root

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    register-with-eureka: 'true'
    instance:
      prefer-ip-address: 'true'
    fetch-registry: 'true'


openapi:
  service:
    title: user-service doc
    version: 1.0.0
    url: http://localhost:8080

springdoc:
  api-docs:
    path: /user-service/v3/api-docs
  swagger-ui:
    path: /user-service/swagger-ui.html

#springdoc:
#  api-docs:
#    enabled: true
#  swagger-ui:
#    enabled: true
#    path: /user-service/swagger-ui.html
#    config-url: /user-service/v3/api-docs/swagger-config
#    urls:
#      - url: /user-service/v3/api-docs
#        name: USER SERVICE
