application:
  message: User service local profile is running

server:
  servlet:
    context-path: /
  port: 8001


logging:
  level:
    org:
      springframework:
        security=DEBUG:

spring:
  application:
    name: user-service
  main:
    allow-bean-definition-overriding: 'true'
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8000
      client:
        registration:
          user-service-client:
            client-id: user-service-client
            client-secret: client-secret
            authorization-grant-type: authorization_code
            redirect-uri: 'http://127.0.0.1:8080/sign-up'
            scope: openid, profile
            provider: gateway-provider
        provider:
          gateway-provider:
            authorization-uri: 'http://127.0.0.1:8000/oauth2/authorize'
            token-uri: 'http://127.0.0.1:8000/oauth2/token'
            user-info-uri: 'http://127.0.0.1:8000/userinfo'
            jwk-set-uri: 'http://127.0.0.1:8000/.well-known/jwks.json'
  r2dbc:
    password: root
    url: r2dbc:mariadb://localhost:3314/user-service-db?allowPublicKeyRetrieval=true
    username: root
  config:
    activate:
      on-profile: local
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    namespace: user-service

springdoc:
  api-docs:
    path: /user-service/v3/api-docs
  swagger-ui:
    path: /user-service/swagger-ui.html

management:
  endpoint:
    env:
      post:
        enabled: true
  health:
    refresh:
      enabled: true