networks:
  my-network:
    driver: bridge

services:
  ### MySQL database for Authentication Service
  db-auth:
    container_name: auth-service-db
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: auth-service-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3313:3306
    expose:
      - 3313
    volumes:
      - auth-data:/var/lib/mysql

  ### MySQL database for User Service
  db-user:
    container_name: user-service-db
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: user-service-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3314:3306
    expose:
      - 3314
    volumes:
      - user-data:/var/lib/mysql

  ### Postgres database for Inventory
  db-inventory:
    container_name: inventory-service-db
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: inventory-service-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5431:5431
    expose:
      - 5431
    command: -p 5431
    volumes:
      - inventory-data:/var/lib/postgresql/data
  ### MySQL database for Orders

  db-orders:
    container_name: orders-service-db
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: orders-service-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3310:3306
    expose:
      - 3310
    volumes:
      - orders-data:/var/lib/mysql
  ### Postgres database for Products

  db-products:
    container_name: products-service-db
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: products-service-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5433:5433
    expose:
      - 5433
    command: -p 5433
    volumes:
      - products-data:/var/lib/postgresql/data
  ### MySQL database for Stores

  db-stores:
    container_name: stores-service-db
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: stores-service-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3311:3306
    expose:
      - 3311
    volumes:
      - stores-data:/var/lib/mysql


volumes:
  inventory-data:
  orders-data:
  products-data:
  stores-data:
  user-data:
  auth-data:

