networks:
  my-network:
    driver: bridge

services:
  ### MySQL database for Authentication Service
  db-auth:
    container_name: auth-service-db
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: auth-service-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3313:3306
    expose:
      - 3313
    volumes:
      - auth-data:/var/lib/mysql
    networks:
      - my-network


  ### MySQL database for User Service
  db-user:
    container_name: user-service-db
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: user-service-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3314:3306
    expose:
      - 3314
    volumes:
      - user-data:/var/lib/mysql
    networks:
      - my-network

  ### Eureka Service
  eureka-service:
    image: dacm/eureka-service:1.0.0-SNAPSHOT
    build:
      context: ./eureka-service
    ports:
      - 8761:8761
    networks:
      - my-network

  ### Authorization Service
  authorization-service:
    image: dacm/authorization-service:1.0.0-SNAPSHOT
    build:
      context: ./authorization-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://auth-service-db:3306/auth-service-db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka/
    ports:
      - 8000:8000
    depends_on:
      - db-auth
      - eureka-service
    networks:
      - my-network

  ### User Service
  user-service:
    image: dacm/user-service:1.0.0-SNAPSHOT
    build:
      context: ./user-service
#    environment:
#      - SPRING_DATASOURCE_URL=r2dbc:mariadb://db-user:3306/user-service-db?allowPublicKeyRetrieval=true
#      - SPRING_DATASOURCE_USERNAME=root
#      - SPRING_DATASOURCE_PASSWORD=root
#      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI=http://authorization-service:8000
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka/
    ports:
      - 8001:8001
    depends_on:
      - db-user
      - authorization-service
      - eureka-service
    networks:
      - my-network

  api-gateway-service:
    image: dacm/api-gateway-service:1.0.0-SNAPSHOT
    build:
      context: ./api-gateway
    ports:
      - 8080:8080
    depends_on:
      - eureka-service
    networks:
      - my-network

volumes:
  user-data:
  auth-data:

