server:
  port: 8080
#  servlet:
#    context-path: /api-gateway
spring:
  application:
    name: api-gateway-client

  cloud:
    gateway:
      httpclient:
        connect-timeout: 20000
        response-timeout: 7s
      routes:
        - id: authorization-service
          uri: lb://authorization-service
          predicates:
            - Path=/oauth2/authorize, /oauth2/token, /userinfo, /.well-known/jwks.json, /authorization-service/v3/api-docs
          filters:
            - StripPrefix=1
            - TokenRelay

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**, /user-service/v3/api-docs
          filters:
            - StripPrefix=1
            - TokenRelay



      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
  #  main:
  #    allow-bean-definition-overriding: true
  #    web-application-type: reactive

  output.ansi.enabled: ALWAYS
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authorization-service:8000
      client:
        registration:
          basic-client:
            client-id: basic-client
            client-secret: client-secret
            authorization-grant-type: authorization_code
            redirect-uri: 'http://127.0.0.1:8080/authorized'
            scope: openid , all
            client-name: BASIC CLIENT
            provider: gateway-provider
            client-authentication-method: basic

          swagger-ui-client:
            client-id: swagger-ui-client
            client-secret: client-secret
            authorization-grant-type: authorization_code
            redirect-uri: 'http://localhost:8080/webjars/swagger-ui/index.html'
            scope: openid, profile
            client-name: SWAGGER-UI CLIENT
            provider: gateway-provider

          pkce-client:
            client-id: pkce-client
            client-secret: client-secret
            authorization-grant-type: authorization_code
            redirect-uri: 'http://127.0.0.1:8080/swagger-ui/'
            scope: openid, ALL
            client-name: PKCE CLIENT
            provider: gateway-provider
            client-authentication-method: basic
        #            redirect-uri: 'http://127.0.0.1:8080/login/oauth2/code/jwk-client'

        provider:
          gateway-provider:
            authorization-uri: 'http://127.0.0.1:8000/oauth2/authorize'
            token-uri: 'http://127.0.0.1:8000/oauth2/token'
            user-info-uri: 'http://127.0.0.1:8000/userinfo'
            jwk-set-uri: 'http://127.0.0.1:8000/.well-known/jwks.json'

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
    instance:
      prefer-ip-address: true
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    namespace: api-gateway-client

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: ApiGateway Service
        primaryName: API Gateway Service
      - url: http://user-service:8001/user-service/v3/api-docs
        name: User service
        primaryName: User service
      - url: http://authorization-service:8000/authorization-service/v3/api-docs
        name: Authorization service
        primaryName: Authorization service